version: "3.9"

services:
  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "8081:27017"
    networks:
      - express_network
  redis:
    container_name: redis-db
    image: redis:latest
    ports:
      - "8082:6379"
    networks:
      - express_network
  express-mongo-redis:
    container_name: express-mongo-redis
    image: mfdsix/express-mongo-redis:1.0
    ports:
      - "3000:3000"
    networks:
      - express_network
    depends_on:
      - mongo
      - redis

networks:
  express_network:
    name: express_network
